import { AuthProvider } from '@/context/AuthContext';
import { UserProvider } from '@/context/UserContext';
import '@/globals.css';
import ClientApolloProvider from '@/lib/apollo/ClientApolloProvider';
import { NotificationProvider } from '@/lib/notification/NotificationProvider';
import { PwaProvider } from '@/lib/pwa';
import QueryProvider from '@/lib/QueryProvider';
import type { Metadata, Viewport } from 'next';
// "Asil" — matches the reference product design (⚡ Asil). Note: an earlier
// infra spike's manifest used "شارژینو" instead — confirm the final brand
// name officially before shipping; this is just the one place to change it.
//
// iOS has no manifest-driven splash screen (Android/Chrome auto-generates
// one from manifest.ts — nothing to do there). Safari only shows one if
// given a pre-rendered PNG per device size, listed below. Generated by
// `node generate-splash.mjs` from public/icons/icon-512.png — if the icon
// or background_color ever changes, regenerate the PNGs and keep this list
// in sync with SPLASH_SCREENS in that script.
//
// NOTE: an in-app React splash (rendering an overlay after mount) can't
// replace this — it can only ever cover the time after JS has already
// loaded and hydrated, not the blank-screen gap before that, which is the
// actual problem on iOS.
const APPLE_STARTUP_IMAGES = [
  {
    url: '/splash/splash-640x1136.png',
    media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-750x1334.png',
    media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-1242x2208.png',
    media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1125x2436.png',
    media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-828x1792.png',
    media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-1242x2688.png',
    media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1170x2532.png',
    media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1179x2556.png',
    media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1284x2778.png',
    media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1290x2796.png',
    media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)',
  },
  {
    url: '/splash/splash-1536x2048.png',
    media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-1668x2224.png',
    media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-1668x2388.png',
    media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)',
  },
  {
    url: '/splash/splash-2048x2732.png',
    media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)',
  },
];

export const metadata: Metadata = {
  title: 'Asil',
  description: 'یافتن ایستگاه شارژ خودرو برقی، مسیریابی و پرداخت از کیف پول',
  // iOS reads these two directly, not from manifest.ts — Safari's manifest
  // icon support is unreliable for the home-screen icon specifically.
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Asil',
    startupImage: APPLE_STARTUP_IMAGES,
  },
  icons: {
    apple: '/icons/apple-touch-icon.png',
  },
};

// viewport-fit=cover + safe-area-inset-* in CSS is what keeps fixed
// headers/footers (map controls, bottom nav) from sitting under the iPhone
// notch/home-indicator once the app is installed to the home screen.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  themeColor: '#0f172a',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" data-theme="mytheme" dir="rtl" className="scroll-smooth">
      <body>
        <ClientApolloProvider>
          <QueryProvider>
            <PwaProvider>
              <AuthProvider>
                <UserProvider>
                  <NotificationProvider>
                    <main className="w-full min-h-dvh">{children}</main>
                  </NotificationProvider>
                </UserProvider>
              </AuthProvider>
            </PwaProvider>
          </QueryProvider>
        </ClientApolloProvider>
      </body>
    </html>
  );
}
